install.packages("devtools")
library("devtools")

install_version("drat", version="0.1.3", type="source")
drat::addRepo(c("OHDSI","cloudyr"))

install_github("OHDSI/CohortMethod", ref="v2.4.4")
install_github("OHDSI/DatabaseConnector", ref="#2ae287e") # v2.0.2
install_github("OHDSI/EmpiricalCalibration", ref="#320f670") # v1.3.5
install_github("OHDSI/FeatureExtraction", ref="v2.1.1")
install_github("OHDSI/OhdsiRTools", ref="#b938cf1") # v1.3.3
install_github("OHDSI/SqlRender", ref="#558bbe0") # 1.4.7
install_github("OHDSI/Cyclops", ref="#08e76d6") # v1.3.1
install_github("OHDSI/PatientLevelPrediction", ref="#ef9eed3") #v1.2.2

install_version("assertthat", version="0.2.0", type="source")
install_version("AUC", version="0.3.0", type="source")
install_version("base64enc", version="0.1-3", type="source")
install_version("BH", version="1.65.0-1", type="source")
install_version("bindr", version="0.1", type="source")
install_version("bindrcpp", version="0.2", type="source")
install_version("bit", version="1.1-12", type="source")
install_version("bitops", version="1.0-6", type="source")
install_version("colorspace", version="1.3-2", type="source")
install_version("crosstalk", version="1.0.0", type="source")
install_version("curl", version="3.0", type="source")
install_version("data.table", version="1.10.4-1", type="source")
install_version("DBI", version="0.7", type="source")
install_version("devtools", version="1.13.3", type="source")
install_version("diagram", version="1.6.4", type="source")
install_version("dichromat", version="2.0-0", type="source")
install_version("digest", version="0.6.12", type="source")
install_version("dplyr", version="0.7.4", type="source")
install_version("DT", version="0.2", type="source")
install_version("evaluate", version="0.10.1", type="source")
install_version("fastmatch", version="1.1-0", type="source")
install_version("ff", version="2.2-13", type="source")
install_version("ffbase", version="0.12.3", type="source")
install_version("formatR", version="1.5", type="source")
install_version("futile.logger", version="1.4.3", type="source")
install_version("futile.options", version="1.0.0", type="source")
install_version("gdtools", version="0.1.6", type="source")
install_version("ggplot2", version="2.2.1", type="source")
install_version("git2r", version="0.19.0", type="source")
install_version("glue", version="1.1.1", type="source")
install_version("gridExtra", version="2.3", type="source")
install_version("gtable", version="0.2.0", type="source")
install_version("hexbin", version="1.27.1", type="source")
install_version("highr", version="0.6", type="source")
install_version("htmltools", version="0.3.6", type="source")
install_version("htmlwidgets", version="0.9", type="source")
install_version("httpuv", version="1.3.5", type="source")
install_version("httr", version="1.3.1", type="source")
install_version("jsonlite", version="1.5", type="source")
install_version("knitr", version="1.17", type="source")
install_version("labeling", version="0.3", type="source")
install_version("lambda.r", version="1.2", type="source")
install_version("lazyeval", version="0.2.0", type="source")
install_version("magrittr", version="1.5", type="source")
install_version("mailR", version="0.4.1", type="source")
install_version("markdown", version="0.8", type="source")
install_version("memoise", version="1.1.0", type="source")
install_version("mime", version="0.5", type="source")
install_version("munsell", version="0.4.3", type="source")
install_version("officer", version="0.1.8", type="source")
install_version("openssl", version="0.9.7", type="source")
install_version("pack", version="0.1-1", type="source")
install_version("packrat", version="0.4.8-1", type="source")
install_version("pkgconfig", version="2.0.1", type="source")
install_version("plogr", version="0.1-1", type="source")
install_version("plotly", version="4.7.1", type="source")
install_version("plyr", version="1.8.4", type="source")
install_version("png", version="0.1-7", type="source")
install_version("purrr", version="0.2.3", type="source")
install_version("PythonInR", version="0.1-3", type="source")
install_version("R.methodsS3", version="1.7.1", type="source")
install_version("R.oo", version="1.21.0", type="source")
install_version("R.utils", version="2.5.0", type="source")
install_version("R6", version="2.2.2", type="source")
install_version("RColorBrewer", version="1.1-2", type="source")
install_version("Rcpp", version="0.12.13", type="source")
install_version("RcppEigen", version="0.3.3.3.0", type="source")
install_version("RcppParallel", version="4.3.20", type="source")
install_version("RCurl", version="1.95-4.8", type="source")
install_version("ReporteRs", version="0.8.8", type="source")
install_version("ReporteRsjars", version="0.0.2", type="source")
install_version("reshape2", version="1.4.2", type="source")
install_version("rJava", version="0.9-8", type="source")
install_version("RJDBC", version="0.2-5", type="source")
install_version("RJSONIO", version="1.3-0", type="source")
install_version("rlang", version="0.1.2", type="source")
install_version("rstudioapi", version="0.7", type="source")
install_version("rvg", version="0.1.6", type="source")
install_version("scales", version="0.5.0", type="source")
install_version("shape", version="1.4.3", type="source")
install_version("shiny", version="1.0.5", type="source")
install_version("snow", version="0.4-2", type="source")
install_version("sourcetools", version="0.1.6", type="source")
install_version("stringi", version="1.1.5", type="source")
install_version("stringr", version="1.2.0", type="source")
install_version("survAUC", version="1.0-5", type="source")
install_version("tibble", version="1.3.4", type="source")
install_version("tidyr", version="0.7.1", type="source")
install_version("tidyselect", version="0.2.2", type="source")
install_version("uuid", version="0.1-2", type="source")
install_version("viridisLite", version="0.2.0", type="source")
install_version("whisker", version="0.3-2", type="source")
install_version("withr", version="2.0.0", type="source")
install_version("xgboost", version="0.6-4", type="source")
install_version("XML", version="3.98-1.9", type="source")
install_version("xml2", version="1.1.1", type="source")
install_version("xtable", version="1.8-2", type="source")
install_version("yaml", version="2.1.14", type="source")
install_version("zip", version="1.0.0", type="source")